import { PrismaClient } from "@prisma/client";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

async function main() {
  const admin = await prisma.admin.upsert({
    where: { email: "admin@petshop.com" },
    update: {},
    create: {
      email: "admin@petshop.com",
      password: await bcrypt.hash("admin123", 10),
    },
  });

  const products = [
    {
      name: "Ração Premium para Cães Adultos - 15kg",
      price: 189.90,
      stock: 45,
      description: "Ração completa e balanceada para cães adultos de todas as raças",
      category: "Cachorro",
    },
    {
      name: "Ração Premium para Cães Filhotes - 10kg",
      price: 159.90,
      stock: 38,
      description: "Ração especial para filhotes com nutrientes essenciais para crescimento",
      category: "Cachorro",
    },
    {
      name: "Ração Super Premium para Cães - 20kg",
      price: 289.90,
      stock: 32,
      description: "Ração super premium com ingredientes selecionados e proteínas de alta qualidade",
      category: "Cachorro",
    },
    {
      name: "Ração para Cães Seniores - 15kg",
      price: 179.90,
      stock: 28,
      description: "Ração formulada para cães idosos com suporte para articulações",
      category: "Cachorro",
    },
    {
      name: "Ração Grain Free para Cães - 12kg",
      price: 249.90,
      stock: 25,
      description: "Ração sem grãos, ideal para cães com sensibilidade alimentar",
      category: "Cachorro",
    },
    {
      name: "Ração Light para Cães - 15kg",
      price: 169.90,
      stock: 30,
      description: "Ração com baixo teor de gordura para controle de peso",
      category: "Cachorro",
    },
    {
      name: "Ração Premium para Gatos Adultos - 10kg",
      price: 149.90,
      stock: 42,
      description: "Ração completa e balanceada para gatos adultos",
      category: "Gato",
    },
    {
      name: "Ração Premium para Gatos Filhotes - 7kg",
      price: 129.90,
      stock: 35,
      description: "Ração especial para filhotes com DHA para desenvolvimento cerebral",
      category: "Gato",
    },
    {
      name: "Ração Super Premium para Gatos - 15kg",
      price: 229.90,
      stock: 28,
      description: "Ração super premium com proteínas de alta qualidade",
      category: "Gato",
    },
    {
      name: "Ração para Gatos Castrados - 10kg",
      price: 159.90,
      stock: 33,
      description: "Ração especial para gatos castrados com controle de peso",
      category: "Gato",
    },
    {
      name: "Ração Grain Free para Gatos - 8kg",
      price: 199.90,
      stock: 27,
      description: "Ração sem grãos para gatos com sensibilidade alimentar",
      category: "Gato",
    },
    {
      name: "Ração Úmida para Gatos - 12 Latas 85g",
      price: 45.90,
      stock: 60,
      description: "Ração úmida em sachê com diversos sabores",
      category: "Gato",
    },
    {
      name: "Petisco para Cães - Ossinho Natural",
      price: 18.90,
      stock: 80,
      description: "Ossinho natural para entreter e limpar os dentes",
      category: "Cachorro",
    },
    {
      name: "Petisco para Cães - Biscoito Premium",
      price: 24.90,
      stock: 65,
      description: "Biscoito crocante com vitaminas e minerais",
      category: "Cachorro",
    },
    {
      name: "Petisco para Gatos - Palitos de Peixe",
      price: 19.90,
      stock: 70,
      description: "Palitos sabor peixe para gatos",
      category: "Gato",
    },
    {
      name: "Petisco para Cães - Tiras de Frango",
      price: 22.90,
      stock: 58,
      description: "Tiras desidratadas de frango 100% natural",
      category: "Cachorro",
    },
    {
      name: "Snack Dental para Cães - 500g",
      price: 32.90,
      stock: 52,
      description: "Snack que ajuda na limpeza dos dentes e redução do tártaro",
      category: "Cachorro",
    },
    {
      name: "Brinquedo para Cães - Corda Nó",
      price: 15.90,
      stock: 75,
      description: "Brinquedo de corda resistente para puxar e brincar",
      category: "Cachorro",
    },
    {
      name: "Brinquedo para Cães - Pelúcia Urso",
      price: 28.90,
      stock: 55,
      description: "Brinquedo de pelúcia macio com guizo interno",
      category: "Cachorro",
    },
    {
      name: "Brinquedo para Cães - Kong Clássico",
      price: 45.90,
      stock: 40,
      description: "Brinquedo interativo resistente para colocar petiscos",
      category: "Cachorro",
    },
    {
      name: "Brinquedo para Cães - Frisbee",
      price: 22.90,
      stock: 48,
      description: "Disco voador resistente para atividades ao ar livre",
      category: "Cachorro",
    },
    {
      name: "Brinquedo para Cães - Bola de Tênis",
      price: 8.90,
      stock: 100,
      description: "Bola de tênis oficial para cães",
      category: "Cachorro",
    },
    {
      name: "Brinquedo para Gatos - Varinha com Penas",
      price: 19.90,
      stock: 62,
      description: "Varinha interativa com penas coloridas para estimular o instinto de caça",
      category: "Gato",
    },
    {
      name: "Brinquedo para Gatos - Arranhador Vertical",
      price: 89.90,
      stock: 25,
      description: "Arranhador vertical com corda e plataforma",
      category: "Gato",
    },
    {
      name: "Brinquedo para Gatos - Bola com Guizo",
      price: 12.90,
      stock: 85,
      description: "Bola colorida com guizo interno para estimular brincadeiras",
      category: "Gato",
    },
    {
      name: "Brinquedo para Gatos - Túnel Interativo",
      price: 65.90,
      stock: 30,
      description: "Túnel dobrável para gatos explorarem e brincarem",
      category: "Gato",
    },
    {
      name: "Brinquedo para Gatos - Rato de Pelúcia",
      price: 14.90,
      stock: 70,
      description: "Rato de pelúcia com catnip para estimular o instinto de caça",
      category: "Gato",
    },
    {
      name: "Coleira para Cães - Couro Genuíno",
      price: 45.90,
      stock: 50,
      description: "Coleira de couro genuíno ajustável com fivela metálica",
      category: null,
    },
    {
      name: "Coleira para Cães - Nylon Refletiva",
      price: 32.90,
      stock: 58,
      description: "Coleira de nylon resistente com tecido refletivo para segurança noturna",
      category: null,
    },
    {
      name: "Guia Retrátil para Cães - 5m",
      price: 79.90,
      stock: 35,
      description: "Guia retrátil com trava automática e cabo ergonômico",
      category: null,
    },
    {
      name: "Guia para Cães - Nylon 1,5m",
      price: 28.90,
      stock: 65,
      description: "Guia de nylon resistente com gancho para coleira",
      category: null,
    },
    {
      name: "Peitoral para Cães - Tamanho M",
      price: 55.90,
      stock: 42,
      description: "Peitoral ajustável com alças reforçadas para maior conforto",
      category: null,
    },
    {
      name: "Caixa de Transporte para Cães - Tamanho G",
      price: 189.90,
      stock: 18,
      description: "Caixa de transporte plástica resistente com portas dianteira e superior",
      category: null,
    },
    {
      name: "Coleira para Gatos - Colar com Guizo",
      price: 18.90,
      stock: 72,
      description: "Coleira ajustável com guizo e fechamento de segurança",
      category: null,
    },
    {
      name: "Caixa de Transporte para Gatos",
      price: 95.90,
      stock: 28,
      description: "Caixa de transporte com portas frontais e laterais",
      category: null,
    },
    {
      name: "Shampoo para Cães - Hipoalergênico 500ml",
      price: 32.90,
      stock: 55,
      description: "Shampoo suave sem fragrâncias para peles sensíveis",
      category: null,
    },
    {
      name: "Shampoo para Cães - Antipulgas 500ml",
      price: 38.90,
      stock: 48,
      description: "Shampoo com ação antipulgas e carrapatos",
      category: null,
    },
    {
      name: "Shampoo para Gatos - Hipoalergênico 300ml",
      price: 28.90,
      stock: 52,
      description: "Shampoo suave específico para gatos",
      category: null,
    },
    {
      name: "Areia Sanitária Aglomerante - 10kg",
      price: 45.90,
      stock: 68,
      description: "Areia que forma bolinhas facilitando a limpeza",
      category: null,
    },
    {
      name: "Areia Sanitária Cristal - 3,6kg",
      price: 35.90,
      stock: 58,
      description: "Areia de sílica com maior absorção e controle de odores",
      category: null,
    },
    {
      name: "Caixa Sanitária para Gatos - Tamanho G",
      price: 42.90,
      stock: 38,
      description: "Caixa sanitária plástica com bordas altas",
      category: null,
    },
    {
      name: "Escova para Cães - Cerdas Macias",
      price: 24.90,
      stock: 62,
      description: "Escova com cerdas macias para pelo curto e longo",
      category: null,
    },
    {
      name: "Escova para Gatos - Remove Pelos",
      price: 22.90,
      stock: 55,
      description: "Escova especial para remover pelos soltos",
      category: null,
    },
    {
      name: "Cortador de Unhas para Cães",
      price: 28.90,
      stock: 45,
      description: "Cortador de unhas profissional com lâmina de aço",
      category: null,
    },
    {
      name: "Cama para Cães - Redonda Tamanho M",
      price: 125.90,
      stock: 32,
      description: "Cama redonda macia e confortável com bordas altas",
      category: null,
    },
    {
      name: "Cama para Cães - Retangular Tamanho G",
      price: 159.90,
      stock: 25,
      description: "Cama retangular grande com espuma de alta densidade",
      category: null,
    },
    {
      name: "Cama para Gatos - Igloo",
      price: 89.90,
      stock: 35,
      description: "Cama tipo igloo com entrada lateral para privacidade",
      category: null,
    },
    {
      name: "Casa para Pet - Plástica Tamanho M",
      price: 189.90,
      stock: 20,
      description: "Casa de plástico resistente com telhado removível",
      category: null,
    },
    {
      name: "Cama Elevada para Cães - Tamanho G",
      price: 145.90,
      stock: 22,
      description: "Cama elevada com tecido respirável e estrutura de metal",
      category: null,
    },
    {
      name: "Comedouro para Cães - Inox Tamanho M",
      price: 35.90,
      stock: 58,
      description: "Comedouro de aço inoxidável com base antiderrapante",
      category: null,
    },
    {
      name: "Comedouro para Cães - Plástico Tamanho G",
      price: 22.90,
      stock: 72,
      description: "Comedouro de plástico resistente e fácil de limpar",
      category: null,
    },
    {
      name: "Comedouro Automático para Gatos - 2,5L",
      price: 199.90,
      stock: 18,
      description: "Comedouro automático com timer programável",
      category: null,
    },
    {
      name: "Bebedouro para Gatos - Fonte Elétrica",
      price: 159.90,
      stock: 25,
      description: "Fonte de água elétrica com filtro e circulação contínua",
      category: null,
    },
    {
      name: "Bebedouro para Cães - Inox Tamanho G",
      price: 42.90,
      stock: 48,
      description: "Bebedouro de aço inoxidável com capacidade de 2 litros",
      category: null,
    },
    {
      name: "Comedouro Duplo para Gatos",
      price: 38.90,
      stock: 52,
      description: "Comedouro duplo com espaço para ração e água",
      category: null,
    },
    {
      name: "Comedouro Lento para Cães",
      price: 45.90,
      stock: 42,
      description: "Comedouro com obstáculos para reduzir velocidade de alimentação",
      category: null,
    },
    {
      name: "Antipulgas e Carrapatos para Cães - Pipeta",
      price: 52.90,
      stock: 55,
      description: "Antipulgas e carrapatos em pipeta de aplicação tópica",
      category: "Farmácia",
    },
    {
      name: "Antipulgas e Carrapatos para Gatos - Pipeta",
      price: 48.90,
      stock: 58,
      description: "Antipulgas e carrapatos em pipeta para gatos",
      category: "Farmácia",
    },
    {
      name: "Vermífugo para Cães - Comprimido",
      price: 35.90,
      stock: 48,
      description: "Vermífugo de amplo espectro para cães",
      category: "Farmácia",
    },
    {
      name: "Vermífugo para Gatos - Comprimido",
      price: 32.90,
      stock: 52,
      description: "Vermífugo de amplo espectro para gatos",
      category: "Farmácia",
    },
    {
      name: "Suplemento para Articulações - 60 comprimidos",
      price: 89.90,
      stock: 35,
      description: "Suplemento com glucosamina e condroitina para saúde articular",
      category: "Farmácia",
    },
    {
      name: "Vitamina para Cães - Complexo B",
      price: 42.90,
      stock: 45,
      description: "Suplemento vitamínico com complexo B para energia",
      category: "Farmácia",
    },
    {
      name: "Óleo de Peixe para Cães - 500ml",
      price: 65.90,
      stock: 38,
      description: "Óleo rico em ômega 3 para pele e pelagem saudável",
      category: "Farmácia",
    },
    {
      name: "Roupa para Cães - Moletom com Capuz Tamanho M",
      price: 55.90,
      stock: 42,
      description: "Moletom quentinho com capuz para proteger do frio",
      category: null,
    },
    {
      name: "Roupa para Cães - Vestido Tamanho P",
      price: 45.90,
      stock: 38,
      description: "Vestido elegante para ocasiões especiais",
      category: null,
    },
    {
      name: "Fantasia para Cães - Super-Herói",
      price: 65.90,
      stock: 28,
      description: "Fantasia divertida para festas e eventos",
      category: null,
    },
    {
      name: "Roupa para Gatos - Suéter Tamanho M",
      price: 42.90,
      stock: 35,
      description: "Suéter confortável para gatos no inverno",
      category: null,
    },
    {
      name: "Aquário Completo - 50 litros",
      price: 289.90,
      stock: 15,
      description: "Aquário completo com filtro, aquecedor e iluminação LED",
      category: null,
    },
    {
      name: "Filtro para Aquário - Interno 200L/h",
      price: 89.90,
      stock: 32,
      description: "Filtro interno com múltiplas etapas de filtragem",
      category: null,
    },
    {
      name: "Aquecedor para Aquário - 100W",
      price: 65.90,
      stock: 38,
      description: "Aquecedor submersível com termostato automático",
      category: null,
    },
    {
      name: "Ração para Peixes - Flocos 500g",
      price: 28.90,
      stock: 55,
      description: "Ração em flocos para peixes tropicais",
      category: null,
    },
    {
      name: "Rede para Aquário",
      price: 12.90,
      stock: 75,
      description: "Rede para captura e manuseio de peixes",
      category: null,
    },
    {
      name: "Gaiola para Pássaros - Tamanho M",
      price: 145.90,
      stock: 22,
      description: "Gaiola espaçosa com comedouros e bebedouros inclusos",
      category: "Aves",
    },
    {
      name: "Ração para Pássaros - Mix de Sementes 1kg",
      price: 18.90,
      stock: 65,
      description: "Mix completo de sementes para pássaros",
      category: "Aves",
    },
    {
      name: "Brinquedo para Pássaros - Balanço",
      price: 22.90,
      stock: 58,
      description: "Balanço colorido para entretenimento",
      category: "Aves",
    },
    {
      name: "Gaiola para Hamster - Tamanho M",
      price: 95.90,
      stock: 28,
      description: "Gaiola com túneis e acessórios para hamsters",
      category: null,
    },
    {
      name: "Ração para Hamster - 500g",
      price: 24.90,
      stock: 52,
      description: "Ração balanceada para hamsters e pequenos roedores",
      category: null,
    },
    {
      name: "Roda para Hamster - Exercício",
      price: 35.90,
      stock: 45,
      description: "Roda silenciosa para exercícios do hamster",
      category: null,
    },
    {
      name: "Ração para Coelho - Premium 2kg",
      price: 42.90,
      stock: 38,
      description: "Ração premium para coelhos com fibras",
      category: null,
    },
  ];

  console.log(`Criando ${products.length} produtos...`);

  for (const product of products) {
    const existing = await prisma.product.findFirst({
      where: { name: product.name },
    });

    if (!existing) {
      await prisma.product.create({
        data: product,
      });
    }
  }

  const totalProducts = await prisma.product.count();
  console.log(`Seed concluído! Total de produtos no banco: ${totalProducts}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

